### ISSUE TITLE
哔哔叨叨里面，滑动特别快的时候只能不能加载更多

### ISSUE THREAD

**Issue by acemurder** [RedrockMobile/CyxbsMobile_Android#39]
一口气滑动到底部，不等他提前加载的话，后面就加载不出来了

**Comment by yyx290799684** [comment]
应该是进入以后 滑到底 正常…然后下拉刷新…就只有第一面能出来，应该是page有问题



发自我的小米手机

zhengyuxuan <notifications@github.com>编写：

一口气滑动到底部，不等他提前加载的话，后面就加载不出来了

---
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/RedrockMobile/CyxbsMobile_Android/issues/39
